Collections:
  - Name: DeiT3
    Metadata:
      Architecture:
        - Attention Dropout
        - Convolution
        - Dense Connections
        - Dropout
        - GELU
        - Layer Normalization
        - Multi-Head Attention
        - Scaled Dot-Product Attention
        - Tanh Activation
    Paper:
      URL: https://arxiv.org/pdf/2204.07118.pdf
      Title: 'DeiT III: Revenge of the ViT'
    README: configs/deit3/README.md
    Code:
      URL:
      Version:

Models:
  - Name: deit3-small-p16-3rdparty_in1k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 4610000000
      Parameters: 22060000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 81.35
        Top 5 Accuracy: 95.31
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_small_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-small-p16-64xb64_in1k-224.py
  - Name: deit3-small-p16-3rdparty_in1k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 15520000000
      Parameters: 22210000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 83.43
        Top 5 Accuracy: 96.68
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_small_384_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-small-p16-64xb64_in1k-384.py
  - Name: deit3-small-p16-3rdparty_in21k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 4610000000
      Parameters: 22060000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 83.06
        Top 5 Accuracy: 96.77
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_small_224_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-small-p16-64xb64_in1k-224.py
  - Name: deit3-small-p16-3rdparty_in21k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 15520000000
      Parameters: 22210000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 84.84
        Top 5 Accuracy: 97.48
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_small_384_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-small-p16-64xb64_in1k-384.py
  - Name: deit3-medium-p16-3rdparty_in1k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 8000000000
      Parameters: 82900000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 82.99
        Top 5 Accuracy: 96.22
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_medium_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-medium-p16-64xb64_in1k-224.py
  - Name: deit3-medium-p16-3rdparty_in21k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 8000000000
      Parameters: 82900000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 84.56
        Top 5 Accuracy: 97.19
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_medium_224_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-medium-p16-64xb64_in1k-224.py
  - Name: deit3-base-p16-3rdparty_in1k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 17580000000
      Parameters: 86590000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 83.80
        Top 5 Accuracy: 96.55
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_base_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-base-p16-64xb64_in1k-224.py
  - Name: deit3-base-p16-3rdparty_in1k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 55540000000
      Parameters: 88880000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.08
        Top 5 Accuracy: 97.25
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_base_384_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-base-p16-64xb32_in1k-384.py
  - Name: deit3-base-p16-3rdparty_in21k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 17580000000
      Parameters: 86590000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.70
        Top 5 Accuracy: 97.75
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_base_224_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-base-p16-64xb64_in1k-224.py
  - Name: deit3-base-p16-3rdparty_in21k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 55540000000
      Parameters: 88880000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 86.73
        Top 5 Accuracy: 98.11
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_base_384_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-base-p16-64xb32_in1k-384.py
  - Name: deit3-large-p16-3rdparty_in1k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 61600000000
      Parameters: 304000000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 84.87
        Top 5 Accuracy: 97.01
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_large_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-large-p16-64xb64_in1k-224.py
  - Name: deit3-large-p16-3rdparty_in1k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 191000000000
      Parameters: 305000000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.82
        Top 5 Accuracy: 97.60
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_large_384_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-large-p16-64xb16_in1k-384.py
  - Name: deit3-large-p16-3rdparty_in21k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 61600000000
      Parameters: 304000000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 86.97
        Top 5 Accuracy: 98.24
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_large_224_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-large-p16-64xb64_in1k-224.py
  - Name: deit3-large-p16-3rdparty_in21k-384
    In Collection: DeiT3
    Metadata:
      FLOPs: 191000000000
      Parameters: 305000000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 87.73
        Top 5 Accuracy: 98.51
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_large_384_21k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-large-p16-64xb16_in1k-384.py
  - Name: deit3-huge-p14-3rdparty_in1k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 167000000000
      Parameters: 632000000
      Training Data:
        - ImageNet-1k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 85.21
        Top 5 Accuracy: 97.36
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_huge_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-huge-p14-64xb32_in1k-224.py
  - Name: deit3-huge-p14-3rdparty_in21k-224
    In Collection: DeiT3
    Metadata:
      FLOPs: 167000000000
      Parameters: 632000000
      Training Data:
        - ImageNet-21k
    Results:
    - Dataset: ImageNet-1k
      Task: Image Classification
      Metrics:
        Top 1 Accuracy: 87.19
        Top 5 Accuracy: 98.26
    Weights:
    Converted From:
      Weights: https://dl.fbaipublicfiles.com/deit/deit_3_huge_224_1k.pth
      Code: https://github.com/facebookresearch/deit/blob/main/models_v2.py#L171
    Config: configs/deit3/deit3-huge-p14-64xb32_in1k-224.py
